config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/categories' => 'pages#categories'
  get '/search' => 'pages#search'
  get '/company/show' => 'pages#show'
  resources :companies, only: [:index, :show]
end

app/views/pages/categories.slim
section
  section.container
    h4
      | 専門業者のご紹介
    section.menu-container
      h4
        | 分野別
      section.category-menu
        ul.category-menu--list
          li
            = link_to "電気・空調設備", "#電気・空調設備", data:{turbolinks: 'false'}
          li
            = link_to "水道・衛生設備", "#水道・衛生設備", data:{turbolinks: 'false'}
          li
            = link_to "防災・防犯設備", "#防災・防犯設備", data:{turbolinks: 'false'}
          li
            = link_to "エレベータ他", "#エレベータ他", data:{turbolinks: 'false'}
          li
            = link_to "屋上防水・建物", "#屋上防水・建物", data:{turbolinks: 'false'}
          li
            = link_to "内装工事", "#内装工事", data:{turbolinks: 'false'}
          li
            = link_to "建物管理", "#建物管理", data:{turbolinks: 'false'}
          li
            = link_to "専門", "#専門", data:{turbolinks: 'false'}
          li
            = link_to "総合ソリューション", "#総合ソリューション", data:{turbolinks: 'false'}
    section.category--list
      section.category-left
        h3
          | 電気・空調設備
        ul.link-list
          li
            = link_to "電気工事（第二種)", companies_path
          li
            = link_to "高圧電気設備保安管理", companies_path
          li
            = link_to "照明設備工事", companies_path
          li
            = link_to "電話工事", companies_path
          li
            = link_to "太陽光発電工事", companies_path
          li
            = link_to "再生可能エネルギー", companies_path
          li
            = link_to "LED照明", companies_path
          li
            = link_to "業務用エアコン", companies_path
          li
            = link_to "家庭用エアコン", companies_path
          li
            = link_to "全館空調システム", companies_path
        h3
          |水道・衛生設備
        ul.link-list
          li
            = link_to "給排水設備工事", companies_path
          li
            = link_to "給排水管工事", companies_path
          li
            = link_to "給排水管ライニング", companies_path
          li
            = link_to "貯水槽方式から直接給水方式への切り替え", companies_path
          li
            = link_to "ガス設備工事", companies_path
          li
            = link_to "プロパンガス", companies_path
          li
            = link_to "阻集器設置", companies_path
          li
            = link_to "ビルピット", companies_path
          li
            = link_to "ボイラー", companies_path

        h3
          | 防災・防犯設備
        ul.link-list
          li
            = link_to "自動火災報知設備", companies_path
          li
            = link_to "排煙・換気設備工事", companies_path
          li
            = link_to "熱・煙感知器／探知機", companies_path
          li
            = link_to "消火設備・消火器", companies_path
          li
            = link_to "避難誘導設備", companies_path
          li
            = link_to "インターホン工事", companies_path
          li
            = link_to "防犯カメラ", companies_path
          li
            = link_to "鍵交換", companies_path
          li 
            = link_to "セキュリティー", companies_path
          li
            = link_to "機械警備", companies_path
          li
            = link_to "シャッター", companies_path


        h3
          | エレベータ・他
        ul.link-list
          li
            = link_to "エレベータ保守", companies_path
          li
            = link_to "エレベータ交換", companies_path
          li
            = link_to "エスカレータ", companies_path
          li
            = link_to "自動ドア", companies_path
          li
            = link_to "看板工事", companies_path
          li
            = link_to "機械式駐車場", companies_path
          li
            = link_to "駐車場運営", companies_path
          li  
            = link_to "駐輪設備", companies_path
          li  
            = link_to "宅配ボックス", companies_path
          li
            = link_to "インターネット・CATV", companies_path

    
      section.category-right
        h3
          | 屋上防水・建物
        ul.link-list
          li
            = link_to "屋上防水工事", companies_path
          li
            = link_to "外壁塗装工事", companies_path
          li
            = link_to "外壁タイル", companies_path
          li
            = link_to "屋上外壁緑化", companies_path
          li
            = link_to "ガラス工事", companies_path
          li
            = link_to "サッシ工事", companies_path
          li
            = link_to "耐震診断", companies_path
          li
            = link_to "耐震工事", companies_path
          li
            = link_to "制振工事", companies_path
          li
            = link_to "アンテナ・ブースター", companies_path
          li
            = link_to "避雷針", companies_path
        h3
          | 内装工事
        ul.link-list
          li
            = link_to "エントランス改装工事", companies_path
          li
            = link_to "館名板・テナント名板", companies_path
          li
            = link_to "集合ポスト", companies_path
          li
            = link_to "共用部改装工事", companies_path
          li
            = link_to "給湯室・トイレ改装", companies_path
          li
            = link_to "和式トイレ洋式化", companies_path
          li
            = link_to "オフィス内装工事", companies_path
          li
            = link_to "貸室原状回復工事", companies_path
          li
            = link_to "居住用貸室リフォーム", companies_path
        h3
          | 建物管理
        ul.link-list
          li
            = link_to "建物管理", companies_path
          li
            = link_to "清掃管理", companies_path
          li
            = link_to "特別清掃", companies_path
          li
            = link_to "排水管洗浄", companies_path
          li
            = link_to "貯水槽点検洗浄", companies_path
          li
            = link_to "排水槽洗浄", companies_path
          li
            = link_to "空気環境測定", companies_path
          li
            = link_to "産業廃棄物処理", companies_path
          li
            = link_to "フロン処理", companies_path
          li
            = link_to "害虫駆除", companies_path
          li
            = link_to "管理支援ソリューション", companies_path
        h3
          | 専門
        ul.link-list
          li
            = link_to "建物調査", companies_path
          li
            = link_to "長期修繕計画作成", companies_path
          li
            = link_to "建物火災保険", companies_path
          li
            = link_to "高所ガラス清掃", companies_path
          li
            = link_to "土地家屋調査士", companies_path
          li
            = link_to "不動産鑑定士", companies_path
          li
            = link_to "不動産担保ローン", companies_path
          li
            = link_to "司法書士", companies_path
          li
            = link_to "建築コンサルタント", companies_path
        h3
          | 総合ソリューション
        ul.link-list
          li
            = link_to "省エネ化", companies_path
          li
            = link_to "快適性向上", companies_path
          li
            = link_to "安全性向上", companies_path
          li
            = link_to "助成金／優遇税の申請", companies_path
          li
            = link_to "管理・制御システム", companies_path
          li
            = link_to "空間演出", companies_path

  = render 'shared/conditions'

app/views/pages/home.slim
section.top-search
section.hero
  section.container
    header.navigation role="banner" 
      .navigation-wrapper
        .logo
          = link_to image_tag("logo.png"), "/" 
        ul.left-menu
          li
            =link_to "さがす", categories_path
        a#js-mobile-menu.navigation-menu-button href="javascript:void(0)"  MENU
        nav role="navigation" 
          ul#js-navigation-menu.navigation-menu.show
            li.nav-link
              =link_to "ここから開始", "#"
            li.nav-link
              =link_to "ヘルプ", "#"
            li.nav-link
              =link_to "登録する", "#"
            li.nav-link
              =link_to "ログイン", "#"

    section.l-banner
      .title
        h1
          | ビル・マンション一棟
          br/
          | 所有者ための
          br/
          | 専門業者探し
      .search
        h2 修繕、信頼、安心
        .search--form.form
          form action="/companies" method="get"
            .form--field
              input type="text" placeholder="カテゴリ" class= "form--field__text"
            .form--field
              input type="text" placeholder="地域" class= "form--field__text"
            .form--action
              button.btn.btn--primary 探す
section.category
  .container
    ul.accordion-tabs
      li.tab-header-and-content
        a.is-active.tab-link href="javascript:void(0)"  電気・空調設備
        .tab-content
          .container
            ul
              li
                = link_to "電気工事（第二種)", companies_path
              li
                = link_to "高圧電気設備保安管理", companies_path
              li
                = link_to "照明設備工事", companies_path
              li
                = link_to "電話工事", companies_path
              li
                = link_to "太陽光発電工事", companies_path
              li
                = link_to "再生可能エネルギー", companies_path
              li
                = link_to "LED照明", companies_path
              li
                = link_to "業務用エアコン", companies_path
              li
                = link_to "家庭用エアコン", companies_path
              li
                = link_to "全館空調システム", companies_path
      li.tab-header-and-content
        a.tab-link href="#"  水道・衛生設備
        .tab-content
          .container
            ul
              li
                = link_to "給排水設備工事", companies_path
              li
                = link_to "給排水管工事", companies_path
              li
                = link_to "給排水管ライニング", companies_path
              li
                = link_to "貯水槽方式から直接給水方式への切り替え", companies_path
              li
                = link_to "ガス設備工事", companies_path
              li
                = link_to "プロパンガス", companies_path
              li
                = link_to "阻集器設置", companies_path
              li
                = link_to "ビルピット", companies_path
              li
                = link_to "ボイラー", companies_path
      li.tab-header-and-content
        a.tab-link href="#"  防災・防犯設備
        .tab-content
          .container
            ul
              li
                = link_to "自動火災報知設備", companies_path
              li
                = link_to "排煙・換気設備工事", companies_path
              li
                = link_to "熱・煙感知器／探知機", companies_path
              li
                = link_to "消火設備・消火器", companies_path
              li
                = link_to "避難誘導設備", companies_path
              li
                = link_to "インターホン工事", companies_path
              li
                = link_to "防犯カメラ", companies_path
              li
                = link_to "鍵交換", companies_path
              li
                = link_to "セキュリティー", companies_path
              li
                = link_to "機械警備", companies_path
              li
                = link_to "シャッター", companies_path
      li.tab-header-and-content
        a.tab-link href="#" エレベータ・他
        .tab-content
          .container
            ul
              li
                = link_to "エレベータ保守", companies_path
              li
                = link_to "エレベータ交換", companies_path
              li
                = link_to "エスカレータ", companies_path
              li
                = link_to "自動ドア", companies_path
              li
                = link_to "看板工事", companies_path
              li
                = link_to "機械式駐車場", companies_path
              li
                = link_to "駐車場運営", companies_path
              li
                = link_to "駐輪設備", companies_path
              li
                = link_to "宅配ボックス", companies_path
              li
                = link_to "インターネット・CATV", companies_path
      li.tab-header-and-content
        a.tab-link href="#" 屋上防水・建物
        .tab-content
          .container
            ul
              li
                = link_to "屋上防水工事", companies_path
              li
                = link_to "外壁塗装工事", companies_path
              li
                = link_to "外壁タイル", companies_path
              li
                = link_to "屋上外壁緑化", companies_path
              li
                = link_to "ガラス工事", companies_path
              li
                = link_to "サッシ工事", companies_path
              li
                = link_to "耐震診断", companies_path
              li
                = link_to "耐震工事", companies_path
              li
                = link_to "制振工事", companies_path
              li
                = link_to "アンテナ・ブースター", companies_path
              li
                = link_to "避雷針", companies_path
      li.tab-header-and-content
        a.tab-link href="#" 内装
        .tab-content
          .container
            ul
              li
                = link_to "エントランス改装工事", companies_path
              li
                = link_to "館名板・テナント名板", companies_path
              li
                = link_to "集合ポスト", companies_path
              li
                = link_to "共用部改装工事", companies_path
              li
                = link_to "給湯室・トイレ改装", companies_path
              li
                = link_to "和式トイレ洋式化", companies_path
              li
                = link_to "オフィス内装工事", companies_path
              li
                = link_to "貸室原状回復工事", companies_path
              li
                = link_to "居住用貸室リフォーム", companies_path
      li.tab-header-and-content
        a.tab-link href="#" 建物管理
        .tab-content
          .container
            ul
              li
                = link_to "建物管理", companies_path
              li
                = link_to "清掃管理", companies_path
              li
                = link_to "特別清掃", companies_path
              li
                = link_to "排水管洗浄", companies_path
              li
                = link_to "貯水槽点検洗浄", companies_path
              li
                = link_to "排水槽洗浄", companies_path
              li
                = link_to "空気環境測定", companies_path
              li
                = link_to "産業廃棄物処理", companies_path
              li
                = link_to "フロン処理", companies_path
              li
                = link_to "害虫駆除", companies_path
              li
                = link_to "管理支援ソリューション", companies_path
      li.tab-header-and-content
        a.tab-link href="#" 専門
        .tab-content
          .container
            ul
              li
                = link_to "建物調査", companies_path
              li
                = link_to "長期修繕計画作成", companies_path
              li
                = link_to "建物火災保険", companies_path
              li
                = link_to "高所ガラス清掃", companies_path
              li
                = link_to "土地家屋調査士", companies_path
              li
                = link_to "不動産鑑定士", companies_path
              li
                = link_to "不動産担保ローン", companies_path
              li
                = link_to "司法書士", companies_path
              li
                = link_to "建築コンサルタント", companies_path
      li.tab-header-and-content
        a.tab-link href="#" 総合ソリューション
        .tab-content
          .container
            ul
              li
                = link_to "省エネ化", companies_path
              li
                = link_to "快適性向上", companies_path
              li
                = link_to "安全性向上", companies_path
              li
                = link_to "助成金／優遇税の申請", companies_path
              li
                = link_to "管理・制御システム", companies_path
              li 
                = link_to "空間演出", companies_path
    .container
      .more
        =link_to "一覧から探す", categories_path
section.company-trust
  .container
    h4.company-trust--title
      | すべて信頼３条件を満たした専門業者のみ
    .company-trust--lists
      .company-trust--list
        =image_tag "user-group.png", class: ''
        h4
          |ビル・マンション
          br/
          |での豊富な実績
        p 
          |ビル・マンションでの施工実績
          br/
          |の豊富な専門業者のみをご紹介
      .company-trust--list
        =image_tag "user-group.png", class: ''
        h4
          |オーナーからの
          br/
          |推薦・紹介
        p 
          |オーナーからの推薦・紹介がある
          br/
          |専門業者のみを確認してご紹介
      .company-trust--list
        =image_tag "user-group.png", class: ''
        h4
          |アフター
          br/
          |サポート体制
        p 
          |アフターサポートの姿勢と体制
          br/
          |が確かな専門業者のみをご紹介

//companies list
section.companies
  .container
    h4
      |お勧め業者のご紹介
    section.companies-list
      ul
        li.block
          =image_tag "company-img.png"
          h5 AAA社
        li.block
          =image_tag "company-img.png"
          h5 AAA社
        li.block
          =image_tag "company-img.png"
          h5 AAA社

        li.block
          =image_tag "company-img.png"
          h5 AAA社
        li.block
          =image_tag "company-img.png"
          h5 AAA社
    section.more
      =link_to "一覧から探す", "#"

//Marketing Information
section.container
  section.marekting-info
    h1 
      |信頼できる建物設備専門業者を見つけて、
      br/
      |無理のない適切なメンテナンスで、
      br/
      |ビル・マンションを100年持たせよう
    section.more
      =link_to "もっと詳しく", "#"
//process
section.process
  .container
    h4 簡単かつ安心です。
    ul
      li.block.process--list
        =image_tag "process_img.png"
        h4  相談のみ歓迎
      li.block.process--list
        =image_tag "process_img.png"
        h4 一括問い合わせ
      li.block.process--list
        =image_tag "process_img.png"
        h4  ビルオサポート

        

app/views/pages/search.slim
section.search-results
  .container.padding-l-r
    section.breadcrum  
      =link_to "専門業者のご紹介", "#" 
      | > 
      = link_to "分野別", "#"
      | > 
      = link_to "屋上防水", "#"
    section.company-trust
      .container.categories-company-trust
        h4.company-trust--title
          | すべて信頼３条件を満たした信頼できる専門業者です。安心してお問い合わせできます。
    section.service-title
      section.aside-title
      section.search-result-title
        h3
          | 検索結果　：
        h3
          span  外壁塗装
          span　屋上防水工事
    section.search-results-container
      aside
        .aside--advance-search
          .search-fields
            form action=""
              label カテゴリー：
              .form--field
                input type="text" class= "form--field__text" placeholder= '屋上防水業者 '
              .form--field
                input type="text" class= "form--field__text" placeholder= '外壁塗装'
              .form--field
                input type="text" class= "form--field__text" placeholder= 'カテゴリー'
              .form--field
                label 地域：
                input type="text" class= "form--field__text" placeholder="地域"
              .form--action
                button.btn.btn--primary 再検索
          hr
          .search-fields
            h3
              | 建物タイプ
            span
              | ビル
            span
              | マンション
          hr
          .search-fields
            h3
              | 建物規模
            span
              | 小規模
            span
              | 中規模
            span
              | 大規模
          hr
          .search-fields
            h3
              | キーワード検索
            form action=""
              .form--field
                input type="text" class= "form--field__text"
              .form--action
                button.btn.btn--primary 探す
      section.company-search-list
        section.company-item data-link='company/show'
          section.company-item-details
            section.company-item-details-wrapper
              h3.company-item--title
                = link_to '田中防水工事株式会社', company_show_path
              section.company-info
                .company-info--tag
                  =link_to '屋上防水 ', '#', class: 'btn btn--primary'
                  =link_to '外壁塗装', '#' , class: 'btn btn--primary'
                  =link_to '太陽発電', '#' , class: 'btn btn--primary'
                .company-info--group
                  section.company-info--building-type
                    = link_to 'ビル', "#", class: 'btn btn-ghost'
                    = link_to 'マンション', "#", class: 'btn btn-ghost'
                  section.company-info--scale
                    span 
                      | 小
                      br/
                      | 規模
                    span 
                      | 中
                      br/
                      | 規模
                    span 
                      | 大
                      br/
                      | 規模 
                  section.save.star-1.company-info--star
                   | 保 存

                p.company-info--desc
                  | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
            section.company-item-details-wrapper--image
              =image_tag "scompay_img.png", class: ''
              p
                | 東京都世田谷区世田谷１−１              
        section.company-item data-link='company/show'
          section.company-item-details
            section.company-item-details-wrapper
              h3.company-item--title
                = link_to '田中防水工事株式会社', company_show_path
              section.company-info
                .company-info--tag
                  =link_to '屋上防水 ', '#', class: 'btn btn--primary'
                  =link_to '外壁塗装', '#' , class: 'btn btn--primary'
                  =link_to '太陽発電', '#' , class: 'btn btn--primary'
                .company-info--group
                  section.company-info--building-type
                    = link_to 'ビル', "#", class: 'btn btn-ghost'
                    = link_to 'マンション', "#", class: 'btn btn-ghost'
                  section.company-info--scale
                    span 
                      | 小
                      br/
                      | 規模
                    span 
                      | 中
                      br/
                      | 規模
                    span 
                      | 大
                      br/
                      | 規模 
                  section.save.star-1.company-info--star
                   | 保 存

                p.company-info--desc
                  | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
            section.company-item-details-wrapper--image
              =image_tag "scompay_img.png", class: ''
              p
                | 東京都世田谷区世田谷１−１              
        section.company-item data-link='company/show'
          section.company-item-details
            section.company-item-details-wrapper
              h3.company-item--title
                = link_to '田中防水工事株式会社', company_show_path
              section.company-info
                .company-info--tag
                  =link_to '屋上防水 ', '#', class: 'btn btn--primary'
                  =link_to '外壁塗装', '#' , class: 'btn btn--primary'
                  =link_to '太陽発電', '#' , class: 'btn btn--primary'
                .company-info--group
                  section.company-info--building-type
                    = link_to 'ビル', "#", class: 'btn btn-ghost'
                    = link_to 'マンション', "#", class: 'btn btn-ghost'
                  section.company-info--scale
                    span 
                      | 小
                      br/
                      | 規模
                    span 
                      | 中
                      br/
                      | 規模
                    span 
                      | 大
                      br/
                      | 規模 
                  section.save.star-1.company-info--star
                   | 保 存

                p.company-info--desc
                  | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
            section.company-item-details-wrapper--image
              =image_tag "scompay_img.png", class: ''
              p
                | 東京都世田谷区世田谷１−１              
        section.company-item data-link='company/show'
          section.company-item-details
            section.company-item-details-wrapper
              h3.company-item--title
                = link_to '田中防水工事株式会社', company_show_path
              section.company-info
                .company-info--tag
                  =link_to '屋上防水 ', '#', class: 'btn btn--primary'
                  =link_to '外壁塗装', '#' , class: 'btn btn--primary'
                  =link_to '太陽発電', '#' , class: 'btn btn--primary'
                .company-info--group
                  section.company-info--building-type
                    = link_to 'ビル', "#", class: 'btn btn-ghost'
                    = link_to 'マンション', "#", class: 'btn btn-ghost'
                  section.company-info--scale
                    span 
                      | 小
                      br/
                      | 規模
                    span 
                      | 中
                      br/
                      | 規模
                    span 
                      | 大
                      br/
                      | 規模 
                  section.save.star-1.company-info--star
                   | 保 存

                p.company-info--desc
                  | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
            section.company-item-details-wrapper--image
              =image_tag "scompay_img.png", class: ''
              p
                | 東京都世田谷区世田谷１−１              
                