config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get '/categories' => 'pages#categories'
  get '/search' => 'pages#search'
  get '/company/show' => 'pages#show'
  resources :companies, only: [:index, :show]
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                                          :integer          not null, primary key
#  name                                        :string
#  characteristic                              :text
#  strengths                                   :text
#  greeting                                    :text
#  prior_explanation                           :text
#  construction_policy                         :text
#  upon_completion                             :text
#  after_support_policy                        :text
#  created_at                                  :datetime         not null
#  updated_at                                  :datetime         not null
#  banner                                      :string
#  logo                                        :string
#  category_1                                  :string
#  category_2                                  :string
#  category_3                                  :string
#  category_4                                  :string
#  business_areaes                             :text
#  business_day_no                             :integer
#  inquiry_member_image1                       :string
#  inquiry_member_image2                       :string
#  url                                         :string
#  address                                     :string
#  telephone                                   :string
#  president                                   :string
#  about_president                             :string
#  main_business                               :string
#  employees                                   :string
#  eligibility                                 :text
#  ei_industry_are                             :string
#  capital_series                              :string
#  permit                                      :string
#  member_organizations                        :string
#  major_customers                             :string
#  performance_content1                        :string
#  performance_content2                        :string
#  performance_content3                        :string
#  performance_content4                        :string
#  performance_content5                        :string
#  performance_content6                        :string
#  performance_image1                          :string
#  performance_image2                          :string
#  performance_image3                          :string
#  performance_image4                          :string
#  performance_image5                          :string
#  performance_image6                          :string
#  building                                    :boolean          default("false")
#  mansion                                     :boolean          default("false")
#  small_scale                                 :boolean          default("false")
#  medium_scale                                :boolean          default("false")
#  large_scale                                 :boolean          default("false")
#  reputation_rate                             :integer          default("0")
#  consult_rate                                :integer          default("0")
#  after_sales_support_rate                    :integer          default("0")
#  estimate_understand_rate                    :integer          default("0")
#  construction_schedule_rate                  :integer          default("0")
#  greeting_residents_concern_adequate_rate    :integer          default("0")
#  quality_construction_satisfactory_rate      :integer          default("0")
#  construction_report_understand_rate         :integer          default("0")
#  estimate_create                             :string
#  description_of_contract                     :string
#  guarantee_of_description                    :string
#  proposed_force                              :boolean          default("false")
#  neighborhood_greeting                       :boolean          default("false")
#  greeting_the_home                           :boolean          default("false")
#  corresponding_night_weekend                 :boolean          default("false")
#  emergency_response                          :boolean          default("false")
#  split_payment                               :boolean          default("false")
#  inquiry_member_name1                        :string
#  inquiry_member_name2                        :string
#  business_area_image                         :string
#  property_scale_image                        :string
#  construction_amount_image                   :string
#  correspondence_trouble_appropriate_n_a_rate :integer          default("0")
#

class Company < ApplicationRecord
  validates_presence_of :name, :characteristic, :strengths, :greeting,
                        :prior_explanation, :construction_policy,
                        :upon_completion, :after_support_policy

  has_many :feedbacks

  mount_uploader :banner, ImageUploader
  mount_uploader :logo, ImageUploader
  mount_uploader :inquiry_member_image1, ImageUploader
  mount_uploader :inquiry_member_image2, ImageUploader
  mount_uploader :performance_image1, ImageUploader
  mount_uploader :performance_image2, ImageUploader
  mount_uploader :performance_image3, ImageUploader
  mount_uploader :performance_image4, ImageUploader
  mount_uploader :performance_image5, ImageUploader
  mount_uploader :performance_image6, ImageUploader
  mount_uploader :business_area_image, ImageUploader
  mount_uploader :property_scale_image, ImageUploader
  mount_uploader :construction_amount_image, ImageUploader

  def company_logo
    logo.present? ? logo.url(:logo) : 'company-logo.png'
  end

  def company_banner
    banner.present? ? banner.url(:banner) : 'top-detail-img.png'
  end

  def company_inquiry_member_image1
    inquiry_member_image1.present? ? inquiry_member_image1.url(:inquiry_member) : 'contact-img.png'
  end

  def company_inquiry_member_image2
    inquiry_member_image2.present? ? inquiry_member_image2.url(:inquiry_member) : 'contact-img1.png'
  end

  def company_performance_image1
    performance_image1.present? ? performance_image1.url(:performance_image) : 'building.png'
  end

  def company_performance_image2
    performance_image2.present? ? performance_image2.url(:performance_image) : 'building-img2.png'
  end

  def company_performance_image3
    performance_image3.present? ? performance_image3.url(:performance_image) : 'building-img3.png'
  end

  def company_performance_image4
    performance_image4.present? ? performance_image4.url(:performance_image) : 'building-img4.png'
  end

  def company_performance_image5
    performance_image5.present? ? performance_image5.url(:performance_image) : 'building-img5.png'
  end

  def company_performance_image6
    performance_image6.present? ? performance_image6.url(:performance_image) : 'building-img6.png'
  end

  def company_business_area_image
    business_area_image.present? ? business_area_image.url(:more_photos) : 'map-img.png'
  end

  def company_property_scale_image
    property_scale_image.present? ? property_scale_image.url(:more_photos) : 'chart-img1.png'
  end

  def company_construction_amount_image
    construction_amount_image.present? ? construction_amount_image.url(:more_photos) : 'chart-img2.png'
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def show
    @company = Company.find(params[:id])
  end

  def index
    @companies = Company.all
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_companies_list.slim
section.company-search-list
  - @companies.each do |company|
    section.company-item data-link="/companies/#{company.id}"
      section.company-item-details
        section.company-item-details-wrapper
          h3.company-item--title
            = link_to company.name, company_path(company)
          section.company-info
            .company-info--tag
              =link_to '屋上防水 ', '#', class: 'btn btn--primary'
              =link_to '外壁塗装', '#' , class: 'btn btn--primary'
              =link_to '太陽発電', '#' , class: 'btn btn--primary'
            .company-info--group
              section.company-info--building-type
                = link_to 'ビル', "#", class: "btn btn-ghost #{company.decorate.chosen(company.building)}"
                = link_to 'マンション', "#", class: "btn btn-ghost #{company.decorate.chosen(company.mansion)}"
              section.company-info--scale
                span class="#{company.decorate.chosen(company.small_scale)} "
                  | 小
                  br/
                  | 規模
                span class="#{company.decorate.chosen(company.medium_scale)} "
                  | 中
                  br/
                  | 規模
                span class="#{company.decorate.chosen(company.large_scale)} "
                  | 大
                  br/
                  | 規模 
              section.save.star-1.company-info--star
               | 保 存

            p.company-info--desc
              | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
        section.company-item-details-wrapper--image
          =image_tag "scompay_img.png", class: ''
          p
            | 東京都世田谷区世田谷１−１

app/views/companies/_feedback_list.slim
- @company.feedbacks.each do |feedback|
  .reputation
    .reputation--info
      = image_tag feedback.feedbacker_image, class: 'reputation--info__user-img'
      .reputation__name 
        br/  
        = feedback.feedbacker_details
    .reputation--feedback
      .reputation--feedback__title
        = feedback.title
      p.reputation--feedback__detail
        = feedback.description

app/views/companies/index.slim
section.search-results
  .container.padding-l-r
    section.breadcrum  
      =link_to "専門業者のご紹介", "#" 
      | > 
      = link_to "分野別", "#"
      | > 
      = link_to "屋上防水", "#"
    section.company-trust
      .container.categories-company-trust
        h4.company-trust--title
          | すべて信頼３条件を満たした信頼できる専門業者です。安心してお問い合わせできます。
    section.service-title
      section.aside-title
      section.search-result-title
        h3
          | 検索結果　：
        h3
          span  外壁塗装
          span　屋上防水工事
    section.search-results-container
      aside
        .aside--advance-search
          .search-fields
            form action=""
              label カテゴリー：
              .form--field
                input type="text" class= "form--field__text" placeholder= '屋上防水業者 '
              .form--field
                input type="text" class= "form--field__text" placeholder= '外壁塗装'
              .form--field
                input type="text" class= "form--field__text" placeholder= 'カテゴリー'
              .form--field
                label 地域：
                input type="text" class= "form--field__text" placeholder="地域"
              .form--action
                button.btn.btn--primary 再検索
          hr
          .search-fields
            h3
              | 建物タイプ
            span
              | ビル
            span
              | マンション
          hr
          .search-fields
            h3
              | 建物規模
            span
              | 小規模
            span
              | 中規模
            span
              | 大規模
          hr
          .search-fields
            h3
              | キーワード検索
            form action=""
              .form--field
                input type="text" class= "form--field__text"
              .form--action
                button.btn.btn--primary 探す
      = render partial: 'companies_list'
      / section.company-search-list
      /   section.company-item data-link='company/show'
      /     section.company-item-details
      /       section.company-item-details-wrapper
      /         h3.company-item--title
      /           = link_to '田中防水工事株式会社', company_show_path
      /         section.company-info
      /           .company-info--tag
      /             =link_to '屋上防水 ', '#', class: 'btn btn--primary'
      /             =link_to '外壁塗装', '#' , class: 'btn btn--primary'
      /             =link_to '太陽発電', '#' , class: 'btn btn--primary'
      /           .company-info--group
      /             section.company-info--building-type
      /               = link_to 'ビル', "#", class: 'btn btn-ghost'
      /               = link_to 'マンション', "#", class: 'btn btn-ghost'
      /             section.company-info--scale
      /               span 
      /                 | 小
      /                 br/
      /                 | 規模
      /               span 
      /                 | 中
      /                 br/
      /                 | 規模
      /               span 
      /                 | 大
      /                 br/
      /                 | 規模 
      /             section.save.star.company-info--star
      /              | 保 存

      /           p.company-info--desc
      /             | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
      /       section.company-item-details-wrapper--image
      /         =image_tag "scompay_img.png", class: ''
      /         p
      /           | 東京都世田谷区世田谷１−１              
      /   section.company-item data-link='company/show'
      /     section.company-item-details
      /       section.company-item-details-wrapper
      /         h3.company-item--title
      /           = link_to '田中防水工事株式会社', company_show_path
      /         section.company-info
      /           .company-info--tag
      /             =link_to '屋上防水 ', '#', class: 'btn btn--primary'
      /             =link_to '外壁塗装', '#' , class: 'btn btn--primary'
      /             =link_to '太陽発電', '#' , class: 'btn btn--primary'
      /           .company-info--group
      /             section.company-info--building-type
      /               = link_to 'ビル', "#", class: 'btn btn-ghost'
      /               = link_to 'マンション', "#", class: 'btn btn-ghost'
      /             section.company-info--scale
      /               span 
      /                 | 小
      /                 br/
      /                 | 規模
      /               span 
      /                 | 中
      /                 br/
      /                 | 規模
      /               span 
      /                 | 大
      /                 br/
      /                 | 規模 
      /             section.save.star.company-info--star
      /              | 保 存

      /           p.company-info--desc
      /             | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
      /       section.company-item-details-wrapper--image
      /         =image_tag "scompay_img.png", class: ''
      /         p
      /           | 東京都世田谷区世田谷１−１              
      /   section.company-item data-link='company/show'
      /     section.company-item-details
      /       section.company-item-details-wrapper
      /         h3.company-item--title
      /           = link_to '田中防水工事株式会社', company_show_path
      /         section.company-info
      /           .company-info--tag
      /             =link_to '屋上防水 ', '#', class: 'btn btn--primary'
      /             =link_to '外壁塗装', '#' , class: 'btn btn--primary'
      /             =link_to '太陽発電', '#' , class: 'btn btn--primary'
      /           .company-info--group
      /             section.company-info--building-type
      /               = link_to 'ビル', "#", class: 'btn btn-ghost'
      /               = link_to 'マンション', "#", class: 'btn btn-ghost'
      /             section.company-info--scale
      /               span 
      /                 | 小
      /                 br/
      /                 | 規模
      /               span 
      /                 | 中
      /                 br/
      /                 | 規模
      /               span 
      /                 | 大
      /                 br/
      /                 | 規模 
      /             section.save.star.company-info--star
      /              | 保 存

      /           p.company-info--desc
      /             | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
      /       section.company-item-details-wrapper--image
      /         =image_tag "scompay_img.png", class: ''
      /         p
      /           | 東京都世田谷区世田谷１−１              
      /   section.company-item data-link='company/show'
      /     section.company-item-details
      /       section.company-item-details-wrapper
      /         h3.company-item--title
      /           = link_to '田中防水工事株式会社', company_show_path
      /         section.company-info
      /           .company-info--tag
      /             =link_to '屋上防水 ', '#', class: 'btn btn--primary'
      /             =link_to '外壁塗装', '#' , class: 'btn btn--primary'
      /             =link_to '太陽発電', '#' , class: 'btn btn--primary'
      /           .company-info--group
      /             section.company-info--building-type
      /               = link_to 'ビル', "#", class: 'btn btn-ghost'
      /               = link_to 'マンション', "#", class: 'btn btn-ghost'
      /             section.company-info--scale
      /               span 
      /                 | 小
      /                 br/
      /                 | 規模
      /               span 
      /                 | 中
      /                 br/
      /                 | 規模
      /               span 
      /                 | 大
      /                 br/
      /                 | 規模 
      /             section.save.star.company-info--star
      /              | 保 存

      /           p.company-info--desc
      /             | 当社は屋上防水工事・塗装工事のアフターサービス体制が万全です。自社で施工スタッフ30名が在籍しており、すべて自社で直接施工を行います。最近では若い技能士も自社で育てています。工法及び保證内容について...
      /       section.company-item-details-wrapper--image
      /         =image_tag "scompay_img.png", class: ''
      /         p
      /           | 東京都世田谷区世田谷１−１              
                

app/views/companies/show.slim
.container
  .company_banner
    .breadcrum  
      =link_to "専門業者のご紹介", "#" 
      | > 
      = link_to "分野別", "#"
      | > 
      = link_to "屋上防水", "#"
    figure
      =image_tag @company.company_banner

    

section.container.modal#my_modal
  section.company-detail
    section.content-nav
      ul
        li.nav-link
          =link_to "概要", "#"
        li.nav-link
          =link_to "サポート", "#サポート", data:{turbolinks: 'false'}
        li.nav-link
          =link_to "実績", "#実績", data:{turbolinks: 'false'}
        li.nav-link
          =link_to "評判", "#評判", data:{turbolinks: 'false'}
    section.about
      .about--heading
        .about--heading-logo
          =image_tag @company.company_logo
        .about--heading-name
          h1
            = @company.name

      section.about--company
        .info
          .info--label 特徴：
          .info--description
            = @company.characteristic.try(:html_safe)
        .info
          .info--label 強み：
          .info--description 
            = @company.strengths.try(:html_safe)
        .info
          .info--label ご挨拶：
          .info--description 
            = @company.greeting.try(:html_safe)
      hr
    section.policy
      a name="サポート"
      h3 工事・サポート方針
      .policy--detail
        ul.policy--detail__item.cost
          li
            span 見積り作成
            span #{@company.estimate_create}
          li
            span 契約の説明
            span #{@company.description_of_contract}
          li
            span 保証の説明
            span #{@company.guarantee_of_description}
        ul.policy--detail__item
          li 
            | 提案力　
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.proposed_force) }"
          li 
            |近隣挨拶　
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.neighborhood_greeting) }"
          li 
            |入居者挨拶　
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.greeting_the_home) }"
        ul.policy--detail__item
          li 
            | 夜間週末対応
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.corresponding_night_weekend) }"
          li 
            | 緊急対応
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.emergency_response) }"
          li 
            | 現地見学可
            span.sm-circle class= "#{ @company.decorate.status_enable(@company.split_payment) }"
      
      .policy--document
        .info 
          .info--label 事前説明：
          .info--description
            = @company.prior_explanation.try(:html_safe)
        .info
          .info--label 工事方針：
          .info--description
            = @company.construction_policy.try(:html_safe)
        .info
          .info--label 完了時：
          .info--description
            = @company.upon_completion.try(:html_safe)
        .info
          .info--label アフターサポート方針：
          .info--description 
            = @company.after_support_policy.try(:html_safe)
    section.contact
      .contact--action
        button.contact--btn 問い合わせ
        .contact--info
          small 返答目安：#{@company.business_day_no}営業日以内
      .contact--save.star-1
        |保 存
    section.performance
      a name="実績"
      .performance--title
        | 実績
      .performance--photos.photos
        ul
          li.block
            .photos--title
              = @company.performance_content1.try(:html_safe)
            =image_tag @company.company_performance_image1, class: 'photos--image'
          li.block
            .photos--title
              = @company.performance_content2.try(:html_safe)
            =image_tag @company.company_performance_image2, class: 'photos--image'
          li.block
            .photos--title
              = @company.performance_content3.try(:html_safe)
            =image_tag @company.company_performance_image3, class: 'photos--image'
          li.block
            .photos--title
              = @company.performance_content4.try(:html_safe)
            =image_tag @company.company_performance_image4, class: 'photos--image'
          li.block
            .photos--title
              = @company.performance_content5.try(:html_safe)
            =image_tag @company.company_performance_image5, class: 'photos--image'
          li.block
            .photos--title
              = @company.performance_content6.try(:html_safe)
            =image_tag @company.company_performance_image6, class: 'photos--image'             
        
        .more
          =link_to "もっと写真を見る", ""
    section.diagram
      fiture.diagram--chart
        figcaption.diagram--chart__title
          |営業地域
        =image_tag @company.company_business_area_image
      figure.diagram--chart
        figcaption.diagram--chart__title
          |物件規模
        =image_tag @company.company_property_scale_image
      figure.diagram--chart
        figcaption.diagram--chart__title
          |工事金額
        =image_tag @company.company_construction_amount_image
      


    section.contact
      .contact--action
        button.contact--btn 問い合わせ
        .contact--info
          small 返答目安：１営業日以内
      .contact--save.star-1
        |保 存
    
    section.review
      a name="評判"
      .review--title
        |評判 10件　
        span.review--title__stars
          span #{show_rating(@company.reputation_rate)}　
      .review--summery-contents
        .review--summery
          .review--type
            span.review--type__name
              | 事前に納得できる相談ができた　
            span.review--type__stars #{show_rating(@company.consult_rate)}
          .review--type
            span.review--type__name
              | アフターサポートの説明があった 
            span.review--type__stars #{show_rating(@company.after_sales_support_rate)} 
          .review--type
            span.review--type__name
              | 見積書の説明はわかりやすかった 
            span.review--type__stars #{show_rating(@company.estimate_understand_rate)}
          .review--type
            span.review--type__name
              |  工事はスケジュール通りだった 
            span.review--type__stars #{show_rating(@company.construction_schedule_rate)}
          .review--type
            span.review--type__name
              |  近隣・入居者への挨拶気遣いは十分だった 
            span.review--type__stars #{show_rating(@company.greeting_residents_concern_adequate_rate)}
          .review--type
            span.review--type__name
              |  施工の質は満足できた 
            span.review--type__stars #{show_rating(@company.quality_construction_satisfactory_rate)}
          .review--type
            span.review--type__name
              |  トラブル（あれば）の対応は適切だった　N/A 
            span.review--type__stars #{show_rating(@company.correspondence_trouble_appropriate_n_a_rate)}
          .review--type
            span.review--type__name
              |　 工事報告書はわかりやすかった
            span.review--type__stars #{show_rating(@company.construction_report_understand_rate)} 
      .reputations
        = render partial: 'feedback_list'
        .reputation--more
          =link_to "他のオーナーの評判を見る", "#"
          
      section.contact
        .contact--action
          button.contact--btn 問い合わせ
          .contact--info
            small 返答目安：１営業日以内
        .contact--save.star-1
          |保 存
  section.company-infomation
    .building
      .building--type
        .building--type__btn 
          = @company.category_1
        .building--type__btn 
          = @company.category_2
      .building--target
        label.building--target__label.label 対象建物
        .building--target__tag-group
          .building--target__tag class="#{@company.decorate.chosen(@company.building)}"
            |ビル
          .building--target__tag class="#{@company.decorate.chosen(@company.mansion)}"
            |マンション
      .building--size
        label.building--target__label.label 対象建物
        .building--size-group
          .building--size__type class="#{@company.decorate.chosen(@company.small_scale)}"
            |小
            br/
            |規模
          .building--size__type class="#{@company.decorate.chosen(@company.medium_scale)}"
            |中
            br/
            |規模
          .building--size__type class="#{@company.decorate.chosen(@company.large_scale)}"
            |大
            br/
            |規模
      .building--area
        .building--area-label
          label.label 営業地域
        .building--area-places
          = @company.business_areaes.try(:html_safe)
    .contact
      .contact--action
        button.contact--btn 問い合わせ
        .contact--info
          small 私たちが#{@company.business_day_no}営業日以内に返信します
      .contact--photo
        figure.contact--photo__img
          =image_tag @company.company_inquiry_member_image1, class:''
          figcaption #{@company.inquiry_member_name1}
        figure.contact--photo__img
          =image_tag @company.company_inquiry_member_image2, class:''
          figcaption #{@company.inquiry_member_name2}
      .contact--save.star-1
        |保 存

    .office-data
      h3 会社データ
      ul 
        li 
          =link_to @company.url, "#"
        li
          span #{@company.address}
        li
          span 電話
          span #{@company.telephone}
        li
          span 代表取締役：
          span #{@company.president} 
        li
          = @company.about_president.try(:html_safe)
        li
          span 主要業務：
          span #{@company.main_business.try(:html_safe)}
        li          
          = @company.about_president.try(:html_safe)
        li.office-data--qualification
          span 資格：
          span
            = @company.eligibility.try(:html_safe)
        li
          span 営業所：
          span
            = @company.ei_industry_are
      .office-data__captal-series
        span 資本・系列：
        span
          = @company.capital_series
      .office-data__proposal
        span 許認可：
        span
          = @company.permit
      .office-data__member
        span 加盟団体：
        span
          = @company.member_organizations
      .office-data__key
        span 主要顧客：
        span
          = @company.major_customers
  = render 'shared/popup'